import {Request,Response} from 'express'; import bcrypt from 'bcryptjs'; import crypto from 'crypto'; import {z} from 'zod'; import {prisma} from '../utils/prisma'; import {signToken} from '../utils/jwt';
const authSchema=z.object({name:z.string().min(2).max(80),email:z.email(),password:z.string().min(8).max(100)});
const loginSchema=z.object({email:z.email(),password:z.string().min(1)});
const cookieOpts={httpOnly:true,sameSite:'lax' as const,secure:process.env.NODE_ENV==='production',maxAge:7*24*60*60*1000,path:'/'};
export async function register(req:Request,res:Response){try{const d=authSchema.parse(req.body); const email=d.email.toLowerCase(); if(await prisma.user.findUnique({where:{email}}))return res.status(409).json({success:false,message:'An account with this email already exists'}); const password=await bcrypt.hash(d.password,12); const user=await prisma.user.create({data:{name:d.name,email,password,portfolio:{create:{slug:await uniqueSlug(d.name)}}},select:{id:true,name:true,email:true}}); res.cookie('token',signToken(user.id),cookieOpts); return res.status(201).json({success:true,data:{user}});}catch(e:any){return res.status(400).json({success:false,message:e?.issues?.[0]?.message||'Invalid registration details'})}}
export async function login(req:Request,res:Response){try{const d=loginSchema.parse(req.body);const user=await prisma.user.findUnique({where:{email:d.email.toLowerCase()}});if(!user||!(await bcrypt.compare(d.password,user.password)))return res.status(401).json({success:false,message:'Invalid email or password'});res.cookie('token',signToken(user.id),cookieOpts);return res.json({success:true,data:{user:{id:user.id,name:user.name,email:user.email}}});}catch{return res.status(400).json({success:false,message:'Invalid login details'})}}
export function logout(_req:Request,res:Response){res.clearCookie('token',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'});res.json({success:true,message:'Logged out'});}
export async function me(req:Request,res:Response){const user=await prisma.user.findUnique({where:{id:req.userId!},select:{id:true,name:true,email:true}});if(!user)return res.status(401).json({success:false,message:'User not found'});res.json({success:true,data:{user}})}
export async function forgotPassword(req:Request,res:Response){const email=String(req.body?.email||'').toLowerCase(); if(!z.email().safeParse(email).success)return res.status(400).json({success:false,message:'Enter a valid email'});const user=await prisma.user.findUnique({where:{email}});let resetToken:string|undefined;if(user){resetToken=crypto.randomBytes(24).toString('hex');await prisma.user.update({where:{id:user.id},data:{resetToken,resetTokenExpiresAt:new Date(Date.now()+30*60*1000)}})};const data:any={message:'If an account exists, a reset link has been prepared.'};if(process.env.NODE_ENV!=='production'&&resetToken)data.resetToken=resetToken;res.json({success:true,data});}
export async function resetPassword(req:Request,res:Response){const s=z.object({token:z.string().min(10),password:z.string().min(8).max(100)});try{const d=s.parse(req.body);const user=await prisma.user.findFirst({where:{resetToken:d.token,resetTokenExpiresAt:{gt:new Date()}}});if(!user)return res.status(400).json({success:false,message:'Reset link is invalid or expired'});await prisma.user.update({where:{id:user.id},data:{password:await bcrypt.hash(d.password,12),resetToken:null,resetTokenExpiresAt:null}});res.json({success:true,message:'Password reset successfully'});}catch{return res.status(400).json({success:false,message:'Invalid reset details'})}}
async function uniqueSlug(name:string){let base=name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'developer';let slug=base;let n=2;while(await prisma.portfolio.findUnique({where:{slug}})){slug=`${base}-${n++}`;}return slug;}
